version: '3.3'
services:
  db:
    image: postgres
    volumes:
      - 'db:/var/lib/postgresql/data'    
  app:
    build: .
    command: puma -C config/puma.rb
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  db: